### ISSUE TITLE
Function _unit.mulr() does not exist

### ISSUE THREAD

**Issue by Pablofero** [nrc-cnrc/MetroloPy#20]
Hello,
I think I have found a typo...
https://github.com/nrc-cnrc/MetroloPy/blob/3458367a6017c65ba0166cc95273b441513fdabb/metrolopy/unit.py#L1575
I have tested the two examples given and I get `AttributeError '_CompositeUnit' object has no attribute 'mulr'`
This could have been caught with a unit tests ;)
Loving this module, keep up the great work!

**Comment by hvparks** [comment]
Oops, I will fix that...

**Comment by hvparks** [comment]
Finally fixed this in version 0.6.2.  Thanks!!
