### ISSUE TITLE
budget() raises BudgetWarning for an uncertainty of 0

### ISSUE THREAD

**Issue by fookatchu** [nrc-cnrc/MetroloPy#21]
Hi,
While trying to validate metrolopy (v0.6.1) with example S9 from [EA-4/02 M: 2013](https://european-accreditation.org/wp-content/uploads/2018/10/ea-4-02-m-rev01-september-2013.pdf), I noticed that an BudgetWarning is raised for uncertainties with a value 0, when trying to create a budget. I don't want to post the whole code so here is a minimal example showcasing this:

```
import metrolopy as uc

x_1 = uc.gummy(42, 0)
x_2 = uc.gummy(42, 1)
y = x_1 - x_2
print(y.budget([x_1, x_2]))
```

the traceback is:
```
gummy.py:2070: BudgetWarning: the x variables are over determined; they cannot all be taken as independant variables
  return Budget(self,xlist,**kwds)
budget.py:443: RuntimeWarning: invalid value encountered in double_scalars
  d = [p*yu/q.u for p,q in zip(s,x)]
Component Value    u |dy/dx|     s
     x[2]  42.0  1.0     1.0  1.00
     x[1]    42    0     nan   nan
        y   0.0  1.0
```

This is by itself not a problem, since the calculation still seems to be correct and the warnings are easily captured. I just wonder if this is an intended behavior?

**Comment by hvparks** [comment]
Good question...  x_1 is not a "random variable" which is why budget does not like it.  But you are right, the warning message is not very helpful for this situation.  I will make a change.

**Comment by hvparks** [comment]
Version 0.6.2 has been releases and warnings are no longer raised if quantities with zero uncertainty are included in a budget.  Thanks!
