### ISSUE TITLE
gummy.ufrom() only works for single characters

### ISSUE THREAD

**Issue by fookatchu** [nrc-cnrc/MetroloPy#22]
According to the docs the utype property of a gummy should accept an arbitrary string, but this only works for single characters, e.G. A/B (which are obvious choices for a utype).
I tried grouping uncertainties according to the source (DUT, REF, ...) and noticed that the gummy.ufrom() method returned a value of 0. Looking at the code, it seems that only single characters are supported. Here is a minimal example:

```
import metrolopy as uc

x_1 = uc.gummy(10.0, 1, utype='A')
x_2 = uc.gummy(20.0, 2, utype='DUT')
y = x_1 - x_2
print(y.ufrom('A'))
print(y.ufrom('DUT'))
```

**Comment by hvparks** [comment]
Thanks!  I will have a new version out in the next few weeks and fix this.

**Comment by hvparks** [comment]
Version 0.6.2 has been release and this bug has been fixed.  Thanks!
