### ISSUE TITLE
0°C - Bug

### ISSUE THREAD

**Issue by userJay** [nrc-cnrc/MetroloPy#25]
If the value 0°C is entered it is automatically converted to - 273.15(15) °C. A Value slightly above ist giving the correct result.
Enclosed my code:

import metrolopy as uc

UUT = uc.gummy(0, 0.15, uunit="°C", unit="°C")
Out[4]: -273.15(15) °C

UUT = uc.gummy(0, 0.15, uunit="degC", unit="degC")
Out[8]: -273.15(15) °C

UUT = uc.gummy(0.1, 0.15, uunit="degC", unit="degC")
Out[10]: 0.10(15) °C

**Comment by userJay** [comment]
Calulations are done correctly - it is an issue if you want to print result.
Error is traceable to: conversion.offset

class OffsetUnit(NonlinearUnit):
       
    def zero(self):
        return -self.conversion.offset

**Comment by userJay** [comment]
I don't get in which this if case makes sens. If anybody can explain I just recommand to kill the if statement.
Here a solution which works fine in my application. 

# Round x to zero if it is smaller that one count in the last
# digit of the expanded uncertainty.
if xabs < 10**uuexp/2:
    if self.unit.linear:
        x = 0
    else:
        x = 0
        # x = self.unit.zero()

**Comment by hvparks** [comment]
Thanks, I will make add the fix!

**Comment by hvparks** [comment]
Version 0.6.2 has been released fixing this bug.  Thanks!
