### ISSUE TITLE
multiplying a gummy with a complex number should create a jummy

### ISSUE THREAD

**Issue by JensReimann** [nrc-cnrc/MetroloPy#30]
Any operation (e.g. multiplication) of a gummy with a complex number raises an exception. It should rather create a jummy.

This probably require only some additional conditional checks in the ummy code to work and would lead to a more expectable behaviour.

**Comment by hvparks** [comment]
Thanks, sorry it took so long to get back to this.  I have added this functionality to version 0.6.3.
