### ISSUE TITLE
Budget Values with Names

### ISSUE THREAD

**Issue by vysiker** [nrc-cnrc/MetroloPy#31]
In the budget values are displayed with names if uunit of output variable is set to % or ppm.

![image](https://user-images.githubusercontent.com/99641322/153823404-cee0e403-8421-4b45-9a1c-f76b95ed05ee.png)

Adding show_name = False to budget.py solved this issue for me:
![image](https://user-images.githubusercontent.com/99641322/153823955-382a362e-1b2b-40ff-b118-730bc7e090d5.png)

Result:
![image](https://user-images.githubusercontent.com/99641322/153824097-66bf37f7-f658-45b0-be6b-3d8fd7841fbf.png)

**Comment by hvparks** [comment]
Thanks I will fix this,  I am way overdue on a new release to fix some other bugs as well.

**Comment by hvparks** [comment]
This should be fixed now in version 0.6.3
