### ISSUE TITLE
Missing Feature: Uncertainty by Observations

### ISSUE THREAD

**Issue by vysiker** [nrc-cnrc/MetroloPy#32]
I am missing a feature for automatic calculation of uncertainty by a given array of observations similliar to GUM Type A Bayes. Please find an example for student distribution assumptions below.

```
from scipy.stats import t
from scipy import special
import numpy as np

def u(x):
    confidence = special.erf(1/np.sqrt(2)) # single standard deviation 68 percent
    return t.ppf(1-(1-confidence)/2, len(x)-1)*x.std(ddof=1)/np.sqrt(len(x))

def mean(x):
    return np.mean(x)
```

**Comment by hvparks** [comment]
Sorry it took me so long to get back to this.  But thanks for the suggestions!

The function uc.mean does this (I am not sure that it worked properly in previous versions but it does now).  However you have to set the probability manually.  I modified the .p property to accept the string 'ssd' as a erf(1/sqrt(2)) but it is still a little klunky:

import metrolopy as uc
import numpy as np

x = np.random.rand(5)
g = uc.mean(x)
g.p = 'ssd'   # set the level of confidence to erf(1/sqrt(2))

Then g.U gives the same answer as your u(x)
