### ISSUE TITLE
UniformDist Error

### ISSUE THREAD

**Issue by vysiker** [nrc-cnrc/MetroloPy#33]
Although the following expressions should be equivalent results differ. Only the latter is correct.

```
tmp = uc.gummy(uc.UniformDist(lower_limit=6,upper_limit=9),unit='pA')
uc.gummy.simulate([tmp],n=1e7)
tmp.hist(p=0.99)
```
![image](https://user-images.githubusercontent.com/99641322/154269573-9078f7b0-bf66-4b67-ac97-92cdfa50058b.png)
![image](https://user-images.githubusercontent.com/99641322/154269707-c6646327-2fea-4437-af0d-04614f9fd252.png)

```
tmp = uc.gummy(uc.UniformDist(center=7.5,half_width=1.5),unit='pA') 
uc.gummy.simulate([tmp],n=1e7)
tmp.hist(p=0.99)
```
![image](https://user-images.githubusercontent.com/99641322/154269637-e515878c-544a-4cb3-89a2-713c2fa783b7.png)
![image](https://user-images.githubusercontent.com/99641322/154269790-f25622d9-9773-49de-968c-742f56050e36.png)

**Comment by hvparks** [comment]
I finally got this fixed, thanks!
