### ISSUE TITLE
Uncertainty not calculated correctly when working with integers as base in exponential functions

### ISSUE THREAD

**Issue by nluetts** [nrc-cnrc/MetroloPy#9]
First of all, thank you for uploading this package, I was look for something like this for a while!

When testing the package (v0.5.4) on a convoluted model function which had a 10**(...) term I found that the uncertainty does not seem to be calculated correctly (double checking with a calculation by hand and the uncertainties package yielded significantly different results). By accident, I changed the integer 10 to a float 10.0**(...) which solved the problem!

Here is a minimal example:

```python
>>> a = uc.gummy(1, u=0.1)
>>> 10**a

10.0 +/- 2.0
```
vs.
```python
>>> a = uc.gummy(1, u=0.1)
>>> 10.0**a

10.0 +/- 2.3
```

**Comment by hvparks** [comment]
Thanks, you are correct, this is a bug.  It has now been fixed in version 0.5.5 now released on GitHub.
